name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x

    name: Test on Node.js ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn install \
            --non-interactive \
            --frozen-lockfile
      - name: Test
        run: yarn test
        env:
          CI: true
